platform:ios,'10.0'

target 'VideoProject' do
	use_frameworks!
	pod 'SwiftyJSON'
	pod 'Alamofire'
	pod 'HandyJSON'
	pod 'SVProgressHUD'
	pod 'MJRefresh'
	pod 'BMPlayer'
    pod 'SnapKit'
    pod 'SDWebImage'
    pod 'RxSwift'
    pod 'RxCocoa'
    #动画资源地址 https://www.lottiefiles.com/?
    pod 'lottie-ios'
end
