platform:ios,'10.0'

#找到flutter module 目录
flutter_module_path = '../flutter_module'

#找到flutter module 目录中的/.ios/Flutter/podhelper.rb文件
load File.join(flutter_module_path,'.ios','Flutter','podhelper.rb')


target 'VideoProject' do
	use_frameworks!
	pod 'Alamofire'
	pod 'HandyJSON'
	pod 'SVProgressHUD'
	pod 'MJRefresh'
	pod 'BMPlayer'
    pod 'SnapKit'
    pod 'SDWebImage'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    #动画资源地址 https://www.lottiefiles.com/?
    pod 'lottie-ios'
  #podhelper.rb文件中的install_all_flutter_pods方法
  install_all_flutter_pods(flutter_module_path)
end
